# Generated by Django 3.2.13 on 2022-05-29 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='partner_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='partner_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_options', models.CharField(blank=True, max_length=200, null=True)),
                ('tenure_options', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit_percentage', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit_type', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='plan_creator', to='plan.partner')),
                ('updated_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='plan_updator', to='plan.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_user', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit_percentage', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_creator', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_plan', to='plan.plans')),
                ('updated_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('selected_tenure', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deposited_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit_percentage', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit_type', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customer_creator', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customer_plan', to='plan.plans')),
                ('updated_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customer_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
